import type { ResourceConfig } from '../types'

const statusField = {
  key: 'status',
  label: 'Status',
  type: 'select' as const,
  options: [
    { label: 'ACTIVE', value: 'ACTIVE' },
    { label: 'INACTIVE', value: 'INACTIVE' },
  ],
}

const genericTextFields = [
  { key: 'name', label: 'Name', placeholder: 'Enter name' },
  { key: 'description', label: 'Description', type: 'textarea' as const, placeholder: 'Enter description' },
]

export const adminModules: ResourceConfig[] = [
  {
    key: 'products',
    label: 'Products',
    shortLabel: 'Products',
    route: 'products',
    basePath: '/api/admin/product',
    fields: [...genericTextFields, { key: 'measureId', label: 'Measure ID', type: 'number', placeholder: '1' }, statusField],
    tableColumns: ['id', 'name', 'description', 'measureId', 'status'],
    description: 'Manage warehouse products and their measurement links.',
  },
  {
    key: 'categories',
    label: 'Categories',
    shortLabel: 'Categories',
    route: 'categories',
    basePath: '/api/admin/category',
    deleteEndpoint: '/deleted',
    fields: [...genericTextFields, statusField],
    tableColumns: ['id', 'name', 'description', 'status'],
    description: 'Create and update product categories.',
  },
  {
    key: 'stock',
    label: 'Stock',
    shortLabel: 'Stock',
    route: 'stock',
    basePath: '/api/admin/stock',
    deleteEndpoint: '/deleted',
    fields: [
      { key: 'productsId', label: 'Product ID', type: 'number', placeholder: '1' },
      { key: 'wareHouseId', label: 'Warehouse ID', type: 'number', placeholder: '1' },
      { key: 'measureId', label: 'Measure ID', type: 'number', placeholder: '1' },
      { key: 'quantity', label: 'Quantity', type: 'number', placeholder: '0' },
      statusField,
    ],
    tableColumns: ['id', 'productsId', 'wareHouseId', 'quantity', 'measureId', 'status'],
    description: 'Track stock rows across warehouses.',
  },
  {
    key: 'orders',
    label: 'Orders',
    shortLabel: 'Orders',
    route: 'orders',
    basePath: '/api/admin/order',
    fields: [
      { key: 'productsId', label: 'Product ID', type: 'number', placeholder: '1' },
      { key: 'wareHouseId', label: 'Warehouse ID', type: 'number', placeholder: '1' },
      { key: 'measureId', label: 'Measure ID', type: 'number', placeholder: '1' },
      { key: 'quantity', label: 'Quantity', type: 'number', placeholder: '0' },
      statusField,
    ],
    tableColumns: ['id', 'productsId', 'wareHouseId', 'quantity', 'measureId', 'status', 'createdAt'],
    description: 'Create orders and manage order workflow.',
    actions: [
      { key: 'release', label: 'Release', endpoint: (id) => `/api/admin/order/release/${id}` },
      { key: 'complete', label: 'Complete', endpoint: (id) => `/api/admin/order/complete/${id}` },
      { key: 'canceled', label: 'Cancel', endpoint: (id) => `/api/admin/order/canceled/${id}` },
    ],
  },
  {
    key: 'incomes',
    label: 'Incomes',
    shortLabel: 'Incomes',
    route: 'incomes',
    basePath: '/api/admin/income',
    fields: [
      { key: 'productsId', label: 'Product ID', type: 'number', placeholder: '1' },
      { key: 'wareHouseId', label: 'Warehouse ID', type: 'number', placeholder: '1' },
      { key: 'measureId', label: 'Measure ID', type: 'number', placeholder: '1' },
      { key: 'quantity', label: 'Quantity', type: 'number', placeholder: '0' },
      { key: 'price', label: 'Price', type: 'number', placeholder: '0' },
      statusField,
    ],
    tableColumns: ['id', 'productsId', 'quantity', 'price', 'measureId', 'status', 'createdAt'],
    description: 'Register inbound stock and review latest receipts.',
  },
  {
    key: 'suppliers',
    label: 'Suppliers',
    shortLabel: 'Suppliers',
    route: 'suppliers',
    basePath: '/api/admin/supplier',
    fields: [
      { key: 'name', label: 'Name', placeholder: 'Supplier name' },
      { key: 'phoneNumber', label: 'Phone number', placeholder: '+998...' },
      { key: 'address', label: 'Address', placeholder: 'Address' },
      statusField,
    ],
    tableColumns: ['id', 'name', 'phoneNumber', 'address', 'status'],
    description: 'Manage supplier contacts and status.',
  },
  {
    key: 'customers',
    label: 'Customers',
    shortLabel: 'Customers',
    route: 'customers',
    basePath: '/api/admin/customer',
    fields: [
      { key: 'name', label: 'Name', placeholder: 'Customer name' },
      { key: 'phoneNumber', label: 'Phone number', placeholder: '+998...' },
      { key: 'address', label: 'Address', placeholder: 'Address' },
      statusField,
    ],
    tableColumns: ['id', 'name', 'phoneNumber', 'address', 'status'],
    description: 'Manage customer profiles used in orders.',
  },
  {
    key: 'warehouses',
    label: 'Warehouses',
    shortLabel: 'Warehouses',
    route: 'warehouses',
    basePath: '/api/admin/warehouse',
    fields: [
      { key: 'name', label: 'Name', placeholder: 'Warehouse name' },
      { key: 'location', label: 'Location', placeholder: 'Location' },
      { key: 'capacity', label: 'Capacity', type: 'number', placeholder: '0' },
      statusField,
    ],
    tableColumns: ['id', 'name', 'location', 'capacity', 'status'],
    description: 'Manage physical warehouse records.',
  },
  {
    key: 'users',
    label: 'Users',
    shortLabel: 'Users',
    route: 'users',
    basePath: '/api/admin/user',
    fields: [
      { key: 'username', label: 'Username', placeholder: 'username' },
      { key: 'password', label: 'Password', placeholder: 'password' },
      { key: 'roles', label: 'Roles', placeholder: 'ROLE_ADMIN,ROLE_USER' },
      statusField,
    ],
    tableColumns: ['id', 'username', 'roles', 'status'],
    description: 'Admin user management and role assignment.',
  },
  {
    key: 'business',
    label: 'Business',
    shortLabel: 'Business',
    route: 'business',
    basePath: '/api/admin/business',
    fields: [...genericTextFields, statusField],
    tableColumns: ['id', 'name', 'description', 'status'],
    description: 'Secondary resource for business settings.',
  },
  {
    key: 'creator',
    label: 'Creator',
    shortLabel: 'Creator',
    route: 'creator',
    basePath: '/api/admin/creator',
    fields: [...genericTextFields, statusField],
    tableColumns: ['id', 'name', 'description', 'status'],
    description: 'Secondary resource for creator records.',
  },
  {
    key: 'employee',
    label: 'Employee',
    shortLabel: 'Employee',
    route: 'employee',
    basePath: '/api/admin/employee',
    fields: [
      { key: 'firstName', label: 'First name', placeholder: 'First name' },
      { key: 'lastName', label: 'Last name', placeholder: 'Last name' },
      { key: 'phoneNumber', label: 'Phone number', placeholder: '+998...' },
      statusField,
    ],
    tableColumns: ['id', 'firstName', 'lastName', 'phoneNumber', 'status'],
    description: 'Secondary resource for employees.',
  },
  {
    key: 'market',
    label: 'Market',
    shortLabel: 'Market',
    route: 'market',
    basePath: '/api/admin/market',
    fields: [...genericTextFields, statusField],
    tableColumns: ['id', 'name', 'description', 'status'],
    description: 'Secondary resource for markets.',
  },
  {
    key: 'measure',
    label: 'Measure',
    shortLabel: 'Measure',
    route: 'measure',
    basePath: '/api/admin/measure',
    fields: [{ key: 'name', label: 'Name', placeholder: 'kg, piece, box' }],
    tableColumns: ['id', 'name'],
    description: 'Manage measurement units.',
  },
  {
    key: 'outgoing-product',
    label: 'Outgoing Product',
    shortLabel: 'Outgoing',
    route: 'outgoing-product',
    basePath: '/api/admin/outgoingProduct',
    fields: [
      { key: 'productsId', label: 'Product ID', type: 'number', placeholder: '1' },
      { key: 'quantity', label: 'Quantity', type: 'number', placeholder: '0' },
      statusField,
    ],
    tableColumns: ['id', 'productsId', 'quantity', 'status'],
    description: 'Secondary resource for outgoing product rows.',
  },
  {
    key: 'position',
    label: 'Position',
    shortLabel: 'Position',
    route: 'position',
    basePath: '/api/admin/position',
    fields: [{ key: 'name', label: 'Name', placeholder: 'Position name' }, statusField],
    tableColumns: ['id', 'name', 'status'],
    description: 'Secondary resource for positions.',
  },
  {
    key: 'room',
    label: 'Room',
    shortLabel: 'Room',
    route: 'room',
    basePath: '/api/admin/room',
    fields: [{ key: 'name', label: 'Name', placeholder: 'Room name' }, statusField],
    tableColumns: ['id', 'name', 'status'],
    description: 'Secondary resource for rooms.',
  },
  {
    key: 'tag',
    label: 'Tag',
    shortLabel: 'Tag',
    route: 'tag',
    basePath: '/api/admin/tag',
    fields: [{ key: 'name', label: 'Name', placeholder: 'Tag name' }, statusField],
    tableColumns: ['id', 'name', 'status'],
    description: 'Secondary resource for tags.',
  },
  {
    key: 'roles',
    label: 'Role List',
    shortLabel: 'Roles',
    route: 'roles',
    basePath: '/api/admin/role/roles',
    supportsPaging: false,
    fields: [{ key: 'name', label: 'Name', placeholder: 'ROLE_ADMIN' }],
    tableColumns: ['id', 'name'],
    description: 'Read and maintain role catalog entries when backend supports it.',
  },
]

export const primaryModules = [
  adminModules.find((item) => item.key === 'products')!,
  adminModules.find((item) => item.key === 'categories')!,
  adminModules.find((item) => item.key === 'stock')!,
  adminModules.find((item) => item.key === 'orders')!,
  adminModules.find((item) => item.key === 'incomes')!,
  adminModules.find((item) => item.key === 'suppliers')!,
  adminModules.find((item) => item.key === 'customers')!,
  adminModules.find((item) => item.key === 'warehouses')!,
  adminModules.find((item) => item.key === 'users')!,
]

export const secondaryModules = adminModules.filter(
  (module) => !primaryModules.some((primary) => primary.key === module.key),
)

export const getModuleByKey = (key: string) => adminModules.find((item) => item.key === key)
